FROM node:10
MAINTAINER Baquiax <alexanderbaquiax@gmail.com>

ENV EMBER_CLI_VERSION 3.4.4
ENV BOWER_VERSION 1.8.4

RUN \
  npm install -g ember-cli@"$EMBER_CLI_VERSION" &&\
  npm install -g bower@"$BOWER_VERSION"

